In [1]:
from time import time
import datetime
from operator import itemgetter
import csv

import utils
import data_utils

import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn import cross_validation as cv
from sklearn.grid_search import RandomizedSearchCV

In [2]:
def convert_to_date(year, month):
    try:
        return datetime.date(int(year), int(month), day=15)
    except ValueError:
        return datetime.date(1900, 1, 1)


def date_from_year_week(year, week):
    try:
        week_str = "%s-%s" % (int(year), int(week))
        return datetime.datetime.strptime(week_str + '-1', "%Y-%W-%w")
    except ValueError:
        return None

In [3]:
all_data, test = data_utils.load_transformed_data()

In [ ]:
all_data.dtypes

In [ ]:
X = all_data[all_data.Store!=600].drop(['Sales', 'Store'], axis=1).values
y = all_data[all_data.Store!=600]['Sales'].values

In [10]:
X, y = data_utils.get_raw_values(all_data)

In [11]:
model = RandomForestRegressor(n_estimators=15, random_state=42, n_jobs=-1)
folds = cv.KFold(n=len(y), n_folds=5, shuffle=True, random_state=42)
scores = cv.cross_val_score(model, X, y, scoring=utils.rmspe_scorer, cv=folds, n_jobs=-1)
print(scores)
print(scores.mean())

[-0.13742266 -0.26576803 -0.13095527 -0.20684339 -0.14367523]
-0.176932916964


start:
[-0.16511325 -0.15585395 -0.2266584  -0.16512512 -0.28311866]
-0.199173877015

+months
[-0.16242305 -0.1533121  -0.22504717 -0.16205143 -0.28189329]
-0.196945408716

+sin, cos seasonality
[-0.14108535 -0.13168708 -0.21152946 -0.15358098 -0.26704529]
-0.180985632914

-dayofyear
[-0.14266081 -0.13174201 -0.20454126 -0.15296239 -0.26540484]
-0.179462261956

-seasonal4c
[-0.14141886 -0.13274221 -0.206645   -0.14583597 -0.26186046]
-0.177700500236

-s3c -s4c
[-0.14047898 -0.13150589 -0.20866296 -0.14388167 -0.26448425]
-0.17780275036

+all saesonal -s4s
[-0.14364824 -0.13259398 -0.20818244 -0.14971055 -0.26862188]
-0.18055142004

-season 3 sin
[-0.14132956 -0.13147346 -0.21041263 -0.14784936 -0.26501719]
-0.179216441027

-s3s -s4c
[-0.14071325 -0.13082087 -0.20937832 -0.15025052 -0.26355209]
-0.17894300806

only s4s
[-0.13986377 -0.12974478 -0.21319377 -0.14553146 -0.25735798]
-0.177138352

compdistance as log1p and not in 4 categories
[-0.1384822  -0.12730175 -0.21560819 -0.14039125 -0.2566874 ]
-0.175694158985

In [ ]:
model = RandomForestRegressor(n_estimators=15, random_state=42, n_jobs=-1)
model.fit(X, y)
y_pred = model.predict(X)
utils.RMSPE(y, y_pred)

In [ ]:
X_test = all_data[all_data.Store==600].drop(['Sales', 'Store'], axis=1).values
y_test = all_data[all_data.Store==600]['Sales'].values
y_pred = model.predict(X_test)
utils.RMSPE(y_test, y_pred)

In [ ]:
start = 200
end = 700

plt.figure(figsize=(20,10))
plt.plot(y_test[start:end])
plt.plot(y_pred[start:end])

In [13]:
X, y = data_utils.get_raw_values(all_data)
X_test, y_test = data_utils.get_raw_values(test)
forest = RandomForestRegressor(n_estimators=30, random_state=42, n_jobs=-1)
forest.fit(X, y)
y_pred = forest.predict(X_test)
data_utils.write_submission(y_pred, test)

In [15]:
test[test.Id>71]

Id  Store  DayOfWeek  Sales  Open  Promo  SchoolHoliday  woy  month  \
3408      72     93          4      0     1      1              0   38      9   
3456      73     94          4      0     1      1              0   38      9   
3504      74     98          4      0     1      1              0   38      9   
3552      75     99          4      0     1      1              0   38      9   
3600      76    100          4      0     1      1              0   38      9   
3648      77    101          4      0     1      1              0   38      9   
3696      78    102          4      0     1      1              0   38      9   
3744      79    105          4      0     1      1              0   38      9   
3792      80    107          4      0     1      1              0   38      9   
3840      81    108          4      0     1      1              0   38      9   
3888      82    109          4      0     1      1              0   38      9   
3936      83    110          4      0     1      1              0   38      9   
3984      84    111          4      0     1      1              0   38      9   
4032      85    112          4      0     1      1              0   38      9   
4080      86    113          4      0     1      1              0   38      9   
4128      87    115          4      0     1      1              0   38      9   
4176      88    117          4      0     1      1              0   38      9   
4224      89    118          4      0     1      1              0   38      9   
4272      90    119          4      0     1      1              0   38      9   
4320      91    120          4      0     1      1              0   38      9   
4368      92    122          4      0     1      1              0   38      9   
4416      93    124          4      0     1      1              0   38      9   
4464      94    126          4      0     1      1              0   38      9   
4512      95    127          4      0     1      1              0   38      9   
4560      96    128          4      0     1      1              0   38      9   
4608      97    129          4      0     1      1              0   38      9   
4656      98    130          4      0     1      1              0   38      9   
4704      99    131          4      0     1      1              0   38      9   
4752     100    132          4      0     1      1              0   38      9   
4800     101    135          4      0     1      1              0   38      9   
...      ...    ...        ...    ...   ...    ...            ...  ...    ...   
39695  41059   1077          6      0     1      0              0   31      8   
39743  41060   1078          6      0     1      0              0   31      8   
39791  41061   1079          6      0     1      0              1   31      8   
39839  41062   1080          6      0     1      0              0   31      8   
39887  41063   1083          6      0     1      0              1   31      8   
39935  41064   1084          6      0     1      0              1   31      8   
39983  41065   1086          6      0     1      0              1   31      8   
40031  41066   1087          6      0     1      0              1   31      8   
40079  41067   1088          6      0     1      0              0   31      8   
40127  41068   1089          6      0     1      0              0   31      8   
40175  41069   1091          6      0     1      0              0   31      8   
40223  41070   1092          6      0     1      0              0   31      8   
40271  41071   1094          6      0     1      0              0   31      8   
40319  41072   1096          6      0     1      0              0   31      8   
40367  41073   1097          6      0     1      0              0   31      8   
40415  41074   1099          6      0     1      0              0   31      8   
40463  41075   1100          6      0     1      0              0   31      8   
40511  41076   1101          6      0    